server:
  port: 9527
spring:
  application:
    name: ics-zuul-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    register-with-eureka: false
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true


zuul:
#  prefix: /ics
  ignored-services: "*" #忽略真实服务名
  routes:
    member.serviceId: ics-member
    member.path: /api/**



info:
  app.name: microservice
  company.name: www.gateway.com
  build.artifactId: microservice-zuul-gateway-9527
  build.version: 1.0-SNAPSHOT