server:
  port: 3344

spring:
  application:
    name: ics-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SillyBoy007/microservice-config.git #git仓库地址
          search-paths: ics-config #git项目的目录
